### ISSUE TITLE
tiledb update

### ISSUE THREAD

**Issue by eddelbuettel** [rwinlib/tiledb#1]
Could you turn on a build of 2.1.4 in light of https://github.com/r-windows/rtools-packages/pull/172 ?  

As far as I know we cannot trigger this -- please let me know if I overlooked anything there.

**Comment by eddelbuettel** [comment]
Another poke:  @jeroen, could you please turn on the build for 2.1.4 when you get a chance?  Many thanks!

**Comment by jeroen** [comment]
Can you send the PR? Just download the files from here: 

 - http://dl.bintray.com/rtools/mingw32/mingw-w64-i686-tiledb-2.1.4-2-any.pkg.tar.xz
 - http://dl.bintray.com/rtools/mingw64/mingw-w64-x86_64-tiledb-2.1.4-2-any.pkg.tar.xz

Extract them and replace the headers and both `libtiledbstatic.a` files.

**Comment by eddelbuettel** [comment]
Sure, I can look into that. Are the files above auto-created from the PR at https://github.com/r-windows/rtools-packages/pull/172 ? I am still a little lost at the process here.

**Comment by eddelbuettel** [comment]
Also, why are `mingw-e64-i686-tiledb-2.1.{0,1,2,3,4}` all `-2` without a matching `-1`?  Where is that revision set?

**Comment by jeroen** [comment]
Yes the files there are automatically deployed from rtools-packages. The revision is the `pkgrel=2` field.

**Comment by eddelbuettel** [comment]
Noted, I will try to remember that next time I update that.  I saw the `pkgrel=2` too but did not know what it did / why it was there.

**Comment by eddelbuettel** [comment]
Done, please see #2

**Comment by eddelbuettel** [comment]
Thanks

**Comment by jeroen** [comment]
Thanks. By the way, you could consider taking things in your own control and host these binaries somewhere yourself, eg where you also host your macos binaries. You are not required to use rwinlib for this, it's just the place where I archive the binaries that I use myself.

**Comment by jeroen** [comment]
OK I don't mind either, just making sure you're not getting blocked when you are waiting for me to host some static files.
